### PR TITLE
Add Download Btn for direct download

### PR DESCRIPTION
**Pull request by chucem**
Was requested https://www.ivelt.com/forum/viewtopic.php?p=5071275#p5071275

I think its cool option, so I added it, feel free to reject it

image

### CODE REVIEW

**Comment by mordechaim** [comment]
Not a bad idea, but why would someone want to download a video instead of just watching it online?

**Comment by chucem** [comment]
you can ask him... maybe to watch later? soon he is going to need a download all button 😄

**Comment by KnaperYaden** [comment]
For Dropbox it isn't really needed, as you have the download option 
image

Maybe for Drive.

> Not a bad idea, but why would someone want to download a video instead of just watching it online?

Not _instead_ but _in addition to_. He watches it online and then decides he also wants to save it.

**Comment by chucem** [comment]
> For Dropbox it isn't really needed, as you have the download option 

not everyone is so tech-savvy like @KnaperYaden

**Comment by KnaperYaden** [comment]
> > For Dropbox it isn't really needed, as you have the download option
> 
> not everyone is so tech-savvy like @KnaperYaden

Understood, but in the Dropbox/Drive page they also need to have "some" understanding to do things.

I saw this more of a need only for Drive, where the current embedded view doesn't have a Download option at all.

**Comment by PupaRebbe** [comment]
> > > For Dropbox it isn't really needed, as you have the download option
> > 
> > 
> > not everyone is so tech-savvy like @KnaperYaden
> 
> Understood, but in the Dropbox/Drive page they also need to have "some" understanding to do things.
> 
> I saw this more of a need only for Drive, where the current embedded view doesn't have a Download option at all.

And also because Meshimer/Geder filter customers can't play Drive videos.

**Pull request merged**
