### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by KnaperYaden**
Added support for Dropbox .mov links.

See https://www.ivelt.com/forum/viewtopic.php?p=5088963#p5088963

### CODE REVIEW

**Comment by mordechaim** [comment]
Thanks, merging

**Comment by mordechaim** [comment]
I made a small formatting change to your commit.

**Comment by KnaperYaden** [comment]
> Thanks, merging

How come the PR says Closed, not Merged?

(If because of the editing, it's best to edit it as part of the PR/commit, so it remains for the records. No?)

**Comment by mordechaim** [comment]
Yes I know, I force pushed.

**Pull request closed without merging**
